server:
  port: 8081
spring:
#数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#按照要求改
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=utf-8
    username: root
    password: root

#mybatis的相关配置
mybatis:
#mapper配置文件
#xml文件定位，默认resource下
  mapper-locations: classpath:xml/*.xml
